version: '2'

services:
  web:
    container_name: web
    restart: always
    build: ./apiserver
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        --workers=2
        --timeout=240
        "apiserver.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/apiserver'
    ports:
      - '8000:8000'
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

